config/routes.rb
Rails.application.routes.draw do
 
 
  root 'songs#index'

  resources :songs
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :update, :edit, :destroy]

  def index
    @songs = Song.all
  end

  def show
  end

  def new
    @song = Song.new
    
  end

  def edit
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to songs_path
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to songs_path
  end

  private

  def set_song
    @song = Song.find(params[:id])
  end

  def song_params
    params.require(:song).permit(:artist, :genre, :top100, :boolean, :top50, :top25)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Billboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="ui container">
  <%= yield %>
</div>
</html>

app/views/songs/_form.html.erb
<br/>
<br/>
<%= form_with(model: song, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist, required: true, placeholder: "artist" %>
  </div>
  <div class="field">
    <%= f.label :genre %>
    <%= f.text_field :genre, required: true, placeholder: "genre" %>
  </div>
  <div class="top100">
    <%= f.label :top100 %>
    <%= f.text_field :phone, placeholder: "top100" %>
  </div>
  <div class="top50">
    <%= f.label :top50 %>
    <%= f.text_field :top50, required: true, placeholder: "top50" %>
  </div>
  <br />
  <br />
  <%= f.submit nil, class: "ui button" %>
<% end %>

app/views/songs/edit.html.erb
<h1>Edit</h1>

<%= render "form", song: @song %>

<%= link_to "Show", song_path(@song) %> 
<br/>
<br/>
<%= link_to "Back", songs_path %>

app/views/songs/index.html.erb
<h1 class="ui header">All Songs</h1>
<table class="ui striped table">
  <thead>
    <tr class="center aligned">
      <th colspan="4"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @songs.each do |song| %>
      <tr class="center aligned">
        <td>
        </td>
        <td><%= link_to "Show", song_path(song) %></td>
        <td><%= link_to "Edit", edit_song_path(song) %></td>
        <td><%= link_to "Destroy", song_path(song), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />
<%= link_to "New song", new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render "form", song: @song %>

<%= link_to "Back", new_song_path %>

app/views/songs/show.html.erb
<h1>Song</h1>
<div class="ui card">
  <div class="content">
    <p class="header">
      <%= @song.artist %> <%= @song.artist %>
    </p>
  </div>
  <div class="extra content">
    <%= link_to 'Edit', edit_song_path(@song) %> |
    <%= link_to 'Back', songs_path %>
  </div>
</div>